import useTranslation from 'next-translate/useTranslation';
import Head from 'next/head';

import type { NextPage } from 'next';

// eslint-disable-next-line react/function-component-definition
const Home: NextPage = () => {
  const { t } = useTranslation('common');

  return (
    <div>
      <Head>
        <title> {`Airweb ${t`E_SHOP`}`}</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.png" rel="icon" />
      </Head>
    </div>
  );
};

export default Home;
