import useTranslation from 'next-translate/useTranslation';
import Head from 'next/head';
import useSWR from 'swr';

import { StaleIndicator } from '@/components/loading';
import { createSSRHttpClient, endPoints, routeNames, ssrRedirect } from '@/support';
import { Category, Product } from '@/types';

import type { NextPageContext } from 'next';

// eslint-disable-next-line react/function-component-definition
export default function Index({
  ssrCategories,
  ssrProducts,
}: {
  ssrProducts: Product[];
  ssrCategories: Category[];
}) {
  const { t } = useTranslation('common');
  const { data: products, isValidating } = useSWR<Product[]>(endPoints.products, {
    fallbackData: ssrProducts,
  });

  const { data: categories } = useSWR<Category[]>(endPoints.categories, {
    fallbackData: ssrCategories,
  });
  const productsByCategory = categories?.map((category) => {
    const productfiltred = products?.filter((product) => product.category_id === category.id);

    return { ...category, productfiltred };
  });

  return (
    <StaleIndicator isValidating={isValidating}>
      <Head>
        <title> {`Airweb ${t`E_SHOP`}`}</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.png" rel="icon" />
      </Head>
      {productsByCategory?.map((c) => (
        <section key={c.id}>
          <h2 className="font-bold">{c.label}</h2>
          <ul>
            {c.productfiltred?.map((p) => (
              <li key={p.id}>{p.label}</li>
            ))}
          </ul>
        </section>
      ))}
    </StaleIndicator>
  );
}

export const getServerSideProps = async ({ req }: NextPageContext) => {
  try {
    const httpClient = createSSRHttpClient(req);
    const ssrProducts = await httpClient.get<Product[]>(endPoints.products);
    const ssrCategories = await httpClient.get<Category[]>(endPoints.categories);

    return {
      props: { ssrProducts, ssrCategories },
    };
  } catch (error) {
    return ssrRedirect(routeNames.error);
  }
};
